### PR TITLE
HV-169: Fix Exceptions Due to Empty ScrollList

### PR DESCRIPTION
**Pull request by timmccall-wf**
Problem
-------

If a ScrollList is initialized with no items, it throws exceptions during interactions.

Solution
--------

Add guards in the appropriate places.

How To +10/QA
-------------

- `grunt qa`
- Visit the ScrollList demo
- Enter `0` for the number of pages
- Try to generate a console error with all the various modes

@robbecker-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wf-uicomponents 1.0.3
		Release Ticket: HY-1862

***
*Last updated on Thursday, January 29 03:23 PM CST*

**Comment by todbachman-wf** [comment]
+1.

**Comment by robbecker-wf** [comment]
+10 nice guards
image

**Comment by robbecker-wf** [comment]
nah I like this guard better 
image

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit test created/updated  
     - Added to example for testing.
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
