### PR TITLE
HY-2862 Increase size of minimum area on track button on scroll bar

### PR DESCRIPTION
**Pull request by patkujawa-wf**
Problem: "When opening a large document in viewer, the hit area of the tracking button on the scroll bar becomes too small. We need to have a minimum size that feels larger - somewhere in the vicinity of 45px vertical."

Solution: Make it so. I noticed that we could have passed this in as an option (and still can), but I didn't want to trace the option passing all the way down from doc_viewer. Plus, if 45px really is a UX minimum for usability, then it should be the default min size, so...

CR: @georgelesica-wf et al
### To +10
- [ ] UX sign-off on the screenshot below (that's as small as the pill will ever get). @jasonmoore-wf (or @ephierisho-wf)
- [x] `grunt qa` and open http://localhost:9000/examples/scroll_list/?totalPages=7. Now change total pages to >7 and verify that the pill never gets smaller than 45px.
  new

This is how small it used to be:
old

### CODE REVIEW

**Comment by georgelesica-wf** [comment]
Looks like Travis failed. Is the config right? The build status icon on the main repo page is broken...

**Comment by patkujawa-wf** [comment]
I fixed the link (was expecting 'workiva', not 'webfilings'). Travis failures:
```
IE 11.0.0 (Windows 7 0.0.0) ERROR
  Unable to get property 'render' of undefined or null reference
  at /home/travis/build/Workiva/wf-uicomponents/src/scroll_list/ScrollList.js:976
IE 11.0.0 (Windows 7 0.0.0) ERROR
  Unable to get property 'render' of undefined or null reference
  at /home/travis/build/Workiva/wf-uicomponents/src/scroll_list/ScrollList.js:976
...
IE 11.0.0 (Windows 7 0.0.0) RenderingHooksInterceptor handleTransformFinished mouse wheel should render the scroll list when position has changed FAILED
	Expected spy render to have been called.
IE 11.0.0 (Windows 7 0.0.0) RenderingHooksInterceptor handleTransformFinished mouse wheel should render the scroll list when position has changed FAILED
	Expected spy render to have been called.
IE 11.0.0 (Windows 7 0.0.0): Executed 604 of 813 (1 FAILED) ERROR (2.692 secs / 2.627 secs)
INFO [launcher.sauce]: Shutting down Sauce Connect
Warning: Task "karma:sauce" failed. Use --force to continue.
```

**Comment by georgelesica-wf** [comment]
+1 That's a lot of copyright notices...

**Comment by tomconnell-wf** [comment]
+10 - I went up to 10000 pages in the scroll list example, and the pill never got smaller than 45 pixels.  I did discover that the pill can be picked/up dragged with a right click.  ¯\_(ツ)_/¯

**Comment by tomconnell-wf** [comment]
Just waiting on UX signoff before merge

**Comment by tomconnell-wf** [comment]
I guess we don't need to wait for +UX, we'll just do another ticket, if something is wrong.

**Comment by tomconnell-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
- [ ] ~~Unit test created/updated~~ N/A
- [ ] All unit tests pass 
- [ ] Rosie has run and reports the proper release ticket

Merging into master.

**Comment by patkujawa-wf** [comment]
@rmconsole-wf it's 2.1.0 yo

**Comment by kevinhale-wf** [comment]
@rmconsole-wf

**Pull request merged**
