### PR TITLE
HV-301: Set Default Scale for Items in ScrollList When Fit is None

### PR DESCRIPTION
**Pull request by timmccall-wf**
Problem
-------

Need a way to scale content that is not fit to the viewport from consuming code.

Solution
--------

Apply a default scale to items when they are not fit to the viewport.

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will not be able to function
		properly because no ticket is included in the title.
		If your team has decided not to use jira please indicate this in rmconsole

***
*Last updated on Tuesday, February 17 06:33 PM CST*

**Comment by todbachman-wf** [comment]
+1.

**Comment by todbachman-wf** [comment]
+1 again.

**Comment by tomconnell-wf** [comment]
+10ed with https://github.com/Workiva/wf-js-viewer/pull/340

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit test created/updated  
- [x] All unit tests pass 

Merging into master.

**Comment by charliekump-wf** [comment]
@rosie  run_merge_script

**Pull request merged**
