### PR TITLE
HY-1870: Fix Orientation Constants

### PR DESCRIPTION
**Pull request by timmccall-wf**
Problem
-------

The code referenced bad constants :/. Fit by orientation broke as a result.

Solution
--------

Update the constant names.

Unit Tests
----------

Covered

How To +10/QA
-------------

@greglittlefield-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wf-uicomponents 1.0.3
		Release Ticket: HY-1862

***
*Last updated on Monday, February 02 04:56 PM CST*

**Comment by greglittlefield-wf** [comment]
Confirmed that behavior works as expected in books on iOS, using this version of wf-uicomponents (pulled in via [wf-book-viewer-mobile#HY-1870_test](https://github.com/Workiva/wf-book-viewer-mobile/compare/HY-1870_test)), and for multiple viewport sizes:
```js
var spoofDocumentViewerSize = function(width, height) {
    document.body.style.width = width;
    document.body.style.height = height;
    document.body.style.minHeight = '0';
    document.body.style.position = 'relative';
    var fakeResizeEvent = document.createEvent('Event');
    fakeResizeEvent.initEvent('resize', false, false);
    window.dispatchEvent(fakeResizeEvent);
};

spoofDocumentViewerSize(window.innerHeight / 2 + 'px', window.innerHeight + 'px')
```

__+10__

**Comment by stephenbush-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit test created/updated  
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
