### PR TITLE
HV-554 Upgrade to lodash 3.6.0

### PR DESCRIPTION
**Pull request by todbachman-wf**
## Problem:
We are using an old version of lodash. The latest version offers features we'd like to take advantage of.

## Solution:
Updated lodash dependency in `bower.json`.

## +10/QA:
1. CI build passes
1. Open the demos and confirm everything behaves as expected
1. Test in your own application

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wf-uicomponents 1.1.4
		Release Ticket: HY-1959

***
*Last updated on Tuesday, April 07 06:12 PM CST*

**Comment by patkujawa-wf** [comment]
+1

**Comment by robbecker-wf** [comment]
examples/require.config.js needs to update lodash path.

**Comment by lancefisher-wf** [comment]
+1

**Comment by robbecker-wf** [comment]
+10
trooper

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated - Not necessary, dependency update.
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
