### PR TITLE
HY-1743 Release wf-uicomponents 1.0.1

### PR DESCRIPTION
**Pull request by charliekump-wf**
PRs contained in this release:

https://github.com/Workiva/wf-uicomponents/pull/122

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wf-uicomponents/compare/1.0.0...Release_1.0.1

How To +10/QA
-------------

```bash
# skip the following steps if you've already initialized the project
git clone git@github.com:Workiva/wf-uicomponents.git
cd wf-uicomponents

# do not skip these!
git fetch && git checkout Release_1.0.1
Run unit tests
```

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wf-uicomponents 1.0.1
		Release Ticket: HY-1743

		This pull is considered the release of wf-uicomponents 1.0.1. 
		This repo will be tagged, release notes will be created, and communication will go out.

***
*Last updated on Friday, January 09 12:02 PM CST*

**Comment by patkujawa-wf** [comment]
+1 +semver

**Comment by robbecker-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by joearceneaux-mf** [comment]
Why am I getting your GitHub notifications?

**Comment by patkujawa-wf** [comment]
@joearceneaux-wf maybe because of the default dev mailing list subscription. Check which repos you're are watching.

**Pull request merged**
