### PR TITLE
HY-1838 Fix require.config in Examples

### PR DESCRIPTION
**Pull request by timmccall-wf**
Problem
-------

No require.cofig path for bowser.

Solution
--------

Add one.

Unit Tests
----------

None needed.

How To +10/QA
-------------

- `init.sh && grunt serve`
- Should be able to view the ScrollList demo, for example.

@robbecker-wf @stephenbush-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will not be able to function
		properly because no ticket is included in the title.

***
*Last updated on Tuesday, January 13 11:44 AM CST*

**Comment by robbecker-wf** [comment]
+1 (I should have added this in a previous PR when bowser was added and missed it. Thanks and sorry)

**Comment by tomconnell-wf** [comment]
+10 - With master, the scrollList demo yielded a Uncaught Error: Script error for: bowser

With this branch, it is gone.

**Comment by charliekump-wf** [comment]
@rmconsole-wf

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated  
    - Not required, config change.
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
